---
version: '3'
services:
    golang:
        build: golang
        ports:
            - "8080:8080"
        volumes:
            - "./volumes/go_src:${GO_PROJECT_DIR}/app"
        working_dir: "${GO_PROJECT_DIR}/app"
        environment:
            GO_WORK_DIR: "${GO_PROJECT_DIR}/app"
            GIT_USER_NAME:
            GIT_USER_EMAIL:
            USER_ID:
            GROUP_ID:
            USERNAME: dev
            GROUPNAME: dev
            HOMEDIR:
            SSH_PRIVATE_KEY:
            SSH_PUBLIC_KEY:
